import React from "react";

import { Card } from "react-bootstrap";
export default class ReadMore extends React.Component {
    render() {
        return (
            <div>
                <div className="bg-blend-darken bg-[url('https://resources.cleancreations.com/wp-content/uploads/2022/04/undefined-Imgur-41.jpg')] -mt-52 h-[50rem] object-none md:object-bottom object-right-bottom bg-cover " >
                    <p className="pt-96 text-center text-5xl md:pl-24 md:pr-24 font-bold text-white">IS YOUR CHILD ADDICTED TO SUGAR? HERE'S WHAT YOU CAN DO</p>
                    <p className="text-white font-normal text-md text-center">APRIL 22, 2022</p>

                </div>
                <div className="container">
                    <p className="text-md text-gray-500 mt-3">As a parent, it can be difficult to ensure that your child makes healthy choices when it comes to food. The majority of children crave sugar regularly for many reasons. While it is normal for a child to want sugary foods, it can become unhealthy in excess. You may be wondering, is your child addicted to sugar? There are several reasons as to why this may be the case, as well as ways you can help your child make healthier choices. </p>
                    <p className="text-3xl font-bold text-gray-500">Sugar Addiction</p>
                    <p className="text-md text-gray-500 mt-3">It is very possible for children, as well as adults, to become <a className="no-underline" href="https://www.goodrx.com/well-being/addiction/how-to-break-sugar-addiction">addicted to sugar</a>. The average American citizen consumes about 19 teaspoons of added sugar a day, which is much more than the recommended amount. According to the <a className="no-underline" href="https://www.heart.org/en/healthy-living/healthy-eating/eat-smart/sugar/added-sugars#:~:text=The%20American%20Heart%20Association%20recommends,day%2C%20or%20about%209%20teaspoons.">American Heart Association</a>, a person should consume no more than 6 to 9 teaspoons a day. Craving sugar in excess, losing control when eating sugary foods, and eating more than planned are all signs that an individual may be addicted to sugar. Sugar fuels the cells in the brain, causing the brain to see sugar as a reward, keeping a person wanting more of it. If an individual eats sugar often, this reinforces the reward and makes it harder to break the habit. </p>
                    <p className="text-md text-gray-500 mt-3">The reason sugar can provide someone with a “rush” is because of carbohydrates. When carbohydrates are quickly turned into glucose in the bloodstream, the blood sugar spikes. While many foods have carbohydrates in them such as fruits, vegetables, and dairy products, these foods have fiber and protein that slow this process down. Foods like soda, candy, and other sugary foods do not have fiber and protein, causing someone’s blood sugar to spike when they eat these types of foods. After eating these foods, the blood sugar in someone’s bloodstream will rapidly drop. As the body moves glucose out of the bloodstream and into the cells, the pancreas makes insulin, resulting in the crash that many experiences. This rapid change can make an individual feel exhausted, making them crave the sugar rush again. </p>
                    <p className="text-md text-gray-500 mt-3">Individuals who often crave things like fries, bread, and chips may have a sugar addiction as well. These starchy foods are broken down into simple sugars once digested and can cause the same type of sugar rush if not combined with a balanced diet. </p>
                    <p className="text-3xl font-bold text-gray-500">Why is a Child Addicted to Sugar?</p>
                    <p className="text-md text-gray-500 mt-3">Children can crave sugar for a variety of reasons. The amniotic fluid found in the womb and breast milk are both sweet which can cause a child to have a preference for sweet foods. Additionally, children use a large amount of energy when growing, causing them to crave carbohydrates to give them energy. These cravings can translate into sweet cravings as sugary foods are high in simple sugars, a type of carbohydrate. </p>
                    <p className="text-3xl font-bold text-gray-500">Signs Your Child is Addicted to Sugar</p>
                    <p className="text-md text-gray-500 mt-3">A child may eat a normal amount of sugar, but there are several instances where they may be craving it in excess. If a child is eating large amounts of food and is still craving sugar following these, then they may be craving sugar too often. This can be addressed by examining their diet and ensuring that they are receiving adequate nutrients in all food groups. If a child is eating at unusual times and is craving sugary foods during these times, this can be a sign that they are not consuming a balanced, nutrient-rich diet, causing them to crave sugary snacks when it is not normal mealtime. </p>
                    <p className="text-3xl font-bold text-gray-500">How to Fix a Sugar Addiction</p>
                    <p className="text-md text-gray-500 mt-3">While many might assume that quitting sugar cold turkey is easy, depriving a child of sugar altogether will most likely not work. A large change in diet like this is too drastic and will be difficult for a child to maintain. Not allowing any sugar will cause a child to only crave it more, making the sugar addiction even more difficult to break. However, it is possible to train a child’s taste buds to enjoy foods that are not as sweet. Cutting small amounts of sugar out of a child’s diet can allow them to slowly begin incorporating other foods into their diet that may not be as sugar-heavy. Adding more fruits and low-fat dairy products can give the same satisfaction that a sugary food can, without the sugar crash later on. Adding less added sugar to foods is another way to slowly lower sugar intake. </p>
                    <p className="text-md text-gray-500 mt-3">Creating a more <a className="no-underline" href="https://www.mayoclinic.org/healthy-lifestyle/childrens-health/in-depth/nutrition-for-kids/art-20049335">balanced diet for a child</a> is a way to ensure they are satisfied and will be less likely to crave excess sugar. Making simple changes such as incorporating more fruits and vegetables, drinking enough water, and avoiding highly processed foods will make a child feel satisfied with what they are eating. Another way to curb sugar cravings is to ensure that a child is receiving enough protein and fiber in their diet. High-protein foods digest more slowly, allowing a child to stay full for longer. Additionally, protein does not spike blood sugar as sugar does. Fiber can help a child feel full without the excess sugar and calories of high-sugar foods. Fiber does not raise the blood sugar, and will not cause the blood sugar crash that sugary foods will. </p>
                    <p className="text-md text-gray-500 mt-3">Exercise is another way to combat sugar cravings. As a child exercises more, they will naturally crave healthier foods. Anything such as running, walking, bike riding, and other simple exercises can be a great addition to a child’s routine to aid them in managing their sugar cravings. </p>
                <p className="text-3xl font-bold text-gray-500">Maintain a Healthy Diet with Clean Creations</p>
                <p className="text-md text-gray-500 mt-3">As a parent, maintaining your child’s diet can be a difficult task. Ensuring that they receive all their necessary nutrients without excess sugars can be taxing. <a className="no-underline" href="/">Clean Creations</a> offers meal plans for your whole family to stay on track. We also offer different packages depending on how busy your family might be. Our menus change regularly, providing the variety that your children want. <a className="no-underline" href="/">Get started with Clean Creations today</a> and begin living a more balanced lifestyle with your family.</p>
                </div>
            </div>
        )
    }
}